from __future__ import annotations

import os
import shutil
import subprocess
from collections.abc import Callable
from pathlib import Path


class AudioEncodingError(RuntimeError):
    pass


class AudioEncodingCancelled(RuntimeError):
    pass


class FfmpegMp3Encoder:
    """Encodes WAV input through a validated local FFmpeg executable."""

    def __init__(self, executable: Path, *, bitrate_kbps: int = 96) -> None:
        self.executable = executable
        self.bitrate_kbps = bitrate_kbps

    @classmethod
    def discover(
        cls,
        configured_path: str | None = None,
        *,
        bitrate_kbps: int = 96,
    ) -> FfmpegMp3Encoder | None:
        candidate = configured_path or shutil.which("ffmpeg")
        if not candidate:
            return None
        executable = Path(candidate).expanduser()
        if not executable.is_absolute():
            return None
        try:
            executable = executable.resolve(strict=True)
        except OSError:
            return None
        if not executable.is_file():
            return None
        try:
            version_probe = subprocess.run(
                [str(executable), "-version"],
                stdin=subprocess.DEVNULL,
                stdout=subprocess.PIPE,
                stderr=subprocess.DEVNULL,
                timeout=5,
                check=False,
                creationflags=_NO_WINDOW,
            )
            encoder_probe = subprocess.run(
                [str(executable), "-hide_banner", "-encoders"],
                stdin=subprocess.DEVNULL,
                stdout=subprocess.PIPE,
                stderr=subprocess.DEVNULL,
                timeout=5,
                check=False,
                creationflags=_NO_WINDOW,
            )
        except (OSError, subprocess.SubprocessError):
            return None
        if (
            version_probe.returncode != 0
            or not version_probe.stdout.startswith(b"ffmpeg version")
            or encoder_probe.returncode != 0
            or b"libmp3lame" not in encoder_probe.stdout
        ):
            return None
        return cls(executable, bitrate_kbps=bitrate_kbps)

    def encode(
        self,
        source_wav: Path,
        target_mp3: Path,
        *,
        title: str,
        should_cancel: Callable[[], bool],
    ) -> None:
        arguments = [
            str(self.executable),
            "-nostdin",
            "-hide_banner",
            "-loglevel",
            "error",
            "-y",
            "-i",
            str(source_wav),
            "-map_metadata",
            "-1",
            "-vn",
            "-codec:a",
            "libmp3lame",
            "-b:a",
            f"{self.bitrate_kbps}k",
            "-ac",
            "1",
            "-metadata",
            f"title={title}",
            "-metadata",
            "comment=Generated by TTS Platform Reader",
            "-f",
            "mp3",
            str(target_mp3),
        ]
        try:
            process = subprocess.Popen(
                arguments,
                stdin=subprocess.DEVNULL,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                shell=False,
                creationflags=_NO_WINDOW,
            )
        except OSError as exc:
            raise AudioEncodingError("FFmpeg could not be started") from exc
        try:
            while True:
                if should_cancel():
                    _terminate(process)
                    raise AudioEncodingCancelled()
                try:
                    return_code = process.wait(timeout=0.2)
                    break
                except subprocess.TimeoutExpired:
                    continue
        except AudioEncodingCancelled:
            raise
        except Exception:
            _terminate(process)
            raise
        if return_code != 0 or not target_mp3.is_file() or target_mp3.stat().st_size == 0:
            target_mp3.unlink(missing_ok=True)
            raise AudioEncodingError("FFmpeg did not produce an MP3 file")


def _terminate(process: subprocess.Popen[bytes]) -> None:
    process.terminate()
    try:
        process.wait(timeout=2)
    except subprocess.TimeoutExpired:
        process.kill()
        process.wait(timeout=2)


_NO_WINDOW = getattr(subprocess, "CREATE_NO_WINDOW", 0) if os.name == "nt" else 0
